name:  Ml

on:
  push:
    branches:
     -master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
  
    steps:
          - name: Install
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v1
          - run : npm install

          
          - name: Make lint
            run : make lint
            
            
            


